#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_NSW 7
#define FILENAME_BUFFER 10
#define LINE_BUFFER 50
#define MAX_IP 1000
#define MIN_PRI 4
#define MAX_PACKET_LENGTH LINE_BUFFER

enum PACKET_TYPE {RELAY, OPEN, ACK, QUERY, ADD};

enum ACTION_TYPE {FORWARD, DROP};

#endif
